version: '3'

services:
  rails_db:
    container_name: rails_db
    image: postgres
    volumes:
      - rails_db_data:/var/lib/postgresql/data
    restart: always

  rails_app:
    container_name: rails_app
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - rails_db
    volumes:
      - .:/app
    ports:
      - 3000:3000
    tty: true

volumes:
    rails_db_data:
